[gitlab]
url = "https://gitlab.com"
token = ""
poll_interval = 1

[telegram]
token = ""
default_chat = 123
message_thread_id = 0
message_template = """
<b>{event_type}</b>
Пользователь: {user}
Время: {timestamp}
Действие: {action}
Ссылка: <a href="{url}">{title}</a>
"""
pipeline_template = """
<b>CI/CD обновление (проект {project_id})</b>
Пользователь: GitLab
Время: {timestamp}
Действие: {description}
Ссылка: <a href="{base_url}/projects/{project_id}">Проект {project_id}</a>{ping}
"""
push_template = """
<b>Push событие (проект {project_id})</b>
Пользователь: {author}
Время: {timestamp}
Действие: Push в ветку {branch}, коммитов: {commit_count}
Ссылка: <a href="{base_url}/projects/{project_id}">Проект {project_id}</a>{ping}
"""
mr_template = """
<b>Merge Request (проект {project_id})</b>
Пользователь: {author}
Время: {timestamp}
Действие: {title} (состояние: {state})
Ссылка: <a href="{base_url}/projects/{project_id}/merge_requests/{iid}">MR #{iid}</a>{ping}
"""
repo_mapping = { "project_123456" = "@telegram_nick1", "project_789012" = "@telegram_nick2" }
